# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22ebcfbbcc8b776426c9d0c4d73158698a9a937e5b8e125f9c1e704c73a8a2763a2af97358a9d8eb86ce7906f52733ca28781d6cf90dfd3567a1d30e6c9e7560

test:
  secret_key_base: 2d35d87801089962441887c8833e7bc5742b19182fbbe79c491054e1d54e34869a4256a21e6278ccd9708162e19cddd47190e6cf549d94ec5b38bc29943e3625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
